### ISSUE TITLE
Finalize where JSON lives & its governance

### ISSUE THREAD

**Issue by aneeshack4** [microsoft/fluentui-token-pipeline#13]
We want to maintain the JSON as a single source of truth for platform-agnostic tokens. Right now this is the fluentui.json file - finalize where the JSON lives and ensure wherever it is, it can take PRs to update it as design system maintainers will need to do this as design language evolves either through the Figma Theme Designer Plugin or directly in this repo.

**Comment by TravisSpomer** [comment]
I'm going to take this one out for now since it's the only issue here that isn't specifically about the pipeline. We'll track it separately.
