### ISSUE TITLE
Add Font Alignment to fluentui-shared.ts

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui-token-pipeline#42]
When defining the alignment for type, being able to define the following: 
```
"Alignment": {
  "Start": { "value": "left"},
  "Center": { "value": "center"},
  "End": { "value": "end"},
  "Justify": { "value": "justify"}
}
```

**Comment by TravisSpomer** [comment]
I've been talking about this with Daisy and we agreed that we can just remove those since we don't have any specific need for them.
