### ISSUE TITLE
Themes and dark mode

### ISSUE THREAD

**Issue by TravisSpomer** [microsoft/fluentui-token-pipeline#9]
We don't currently have a solution designed for how we'll support different themes and dark mode.

Each platform export will also need to handle this differently: for example, CSS might use a single file with `@media` queries for each theme, or top-level classes that redefine each of the CSS variables coming from tokens. But iOS might include per-theme values all the way on the leaf nodes: for example, they might want ButtonRootFillColorHover to be exported as ButtonRootFillColorHover.Dark, ButtonRootFillColorHover.Light, and so on.

Entire themes might also be platform-specific as well.

**Comment by kikisaints** [comment]
I imagine entire themes will be platform specific, is this not something we can easily extend the transforms to handle?
